AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Devlab example using SAM

Mappings:
  DBConfig:
    DB:
      Name: 'myapp-db'

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: example_app/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DDB_TABLE_NAME: !FindInMap [DBConfig, DB, Name]
          REGION: !Sub ${AWS::Region}
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !FindInMap [DBConfig, DB, Name]
      KeySchema:
        - AttributeName: Artist
          KeyType: HASH
        - AttributeName: Album
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: Artist
          AttributeType: S
        - AttributeName: Album
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
